trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "==== ACCOUNT ===="
      az account show

      echo "==== RESOURCE GROUPS ===="
      az group list -o table